# Assignment

Import numpy as np

In [35]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [36]:
l1=[1,2,3,4,5]
n1=np.array(l1)
print(n1)

[1 2 3 4 5]


Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [37]:
matrix1=[[1,2,3],[4,5,6],[7,8,9]]
n2=np.array(matrix1)
print(n2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [38]:
n3=np.arange(1,19,2)
n3.reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [39]:
np.random.randint(0,10,10)


array([9, 1, 0, 1, 0, 7, 3, 3, 3, 9])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [40]:
r=np.arange(1,6)
a1=r.reshape(5,1)
a1

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [41]:
a1.shape

(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [42]:
a1=np.arange(1,11)
print(a1)
print(a1[2])
print(a1[3])
print(a1[8])


[ 1  2  3  4  5  6  7  8  9 10]
3
4
9


Print alternate elements of that array

In [43]:
print(a1[0:10:2])


[1 3 5 7 9]


Change last 3 elements into 100 using broadcasting and print

In [44]:
a1[7:10]=100
a1

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [45]:
r1=np.arange(1,26)
r2=r1.reshape(5,5)
print(r2)
r2[1:4,1:4]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])